### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by lrusnac** [santinic/how2#1]
`$ how2 python request headers`
```
Cannot fetch answers from Stackoverflow.
TypeError: Cannot read property 'body_markdown' of undefined
```

**Comment by oskarkrawczyk** [comment]
Yep, getting the same thing on some questions, for example:

```
→ how2 get viewport height with javascript
Cannot fetch answers from Stackoverflow.
TypeError: Cannot read property 'body_markdown' of undefined```

**Comment by santinic** [comment]
thanks, fixing it.

**Comment by santinic** [comment]
it does work if you use -l properly

how2 -l python request headers
how2 -l javascript get viewport height

but it should behave like that anyhow.

**Comment by danielkop** [comment]
Suggested a fix for this with #6

**Comment by santinic** [comment]
Fixed in 1.0.5, update with:

npm update -g how2

**Comment by wolfo** [comment]
Still happening to me with macOS 10.12.1, node 7.0.0, how2 1.1.0: 
```
user@pro:~$ how2 -l python request headers
/usr/local/lib/node_modules/how2/node_modules/devnull/transports/transport.js:59
Transport.prototype.__proto__ = EventEmitter.prototype;
                                            ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/how2/node_modules/devnull/transports/transport.js:59:45)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/how2/node_modules/devnull/transports/stream.js:8:17)
    at Module._compile (module.js:573:32)
```
